name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
        source-url: https://nuget.pkg.github.com/bstadick/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Clean with dotnet
      run: dotnet clean --configuration Release
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
    - name: Pack with dotnet
      run: dotnet pack --configuration Release
    - name: Deploy to GPR with dotnet
      run: dotnet nuget push "bin/Release/*.nupkg"
